# Generated by Django 5.1.5 on 2025-08-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehistory',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamehistory',
            name='player',
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='game_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='game_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='player_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='player_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
