# Generated by Django 5.1.5 on 2025-08-21 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0002_remove_gamehistory_game_remove_gamehistory_player_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamehistory',
            old_name='game_id',
            new_name='game_id_snapshot',
        ),
        migrations.RenameField(
            model_name='gamehistory',
            old_name='game_name',
            new_name='game_name_snapshot',
        ),
        migrations.RenameField(
            model_name='gamehistory',
            old_name='player_id',
            new_name='player_id_snapshot',
        ),
        migrations.RenameField(
            model_name='gamehistory',
            old_name='player_username',
            new_name='player_username_snapshot',
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamedevelopment.gametable'),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamedevelopment.player'),
        ),
    ]
