# Generated by Django 5.1.5 on 2025-08-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0003_rename_game_id_gamehistory_game_id_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_active',
        ),
    ]
