# Generated by Django 5.1.5 on 2025-02-06 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0003_remove_bet_action_bet_bet_action_gametable_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10)),
                ('suit', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='gametable',
            name='current_turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gametable',
            name='round_status',
            field=models.CharField(choices=[('pre-flop', 'Pre-flop'), ('post-flop', 'Post-flop'), ('showdown', 'Showdown')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedevelopment.gametable')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedevelopment.player')),
            ],
        ),
    ]
