# Generated by Django 5.1.5 on 2025-02-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0004_card_gametable_current_turn_gametable_round_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_packed',
        ),
        migrations.AlterField(
            model_name='gametable',
            name='round_status',
            field=models.CharField(choices=[('betting', 'Betting'), ('waiting', 'Waiting'), ('showdown', 'Showdown')], max_length=50),
        ),
    ]
