# Generated by Django 5.1.5 on 2025-08-24 10:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0005_earnedcoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='duration_days',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='redemption_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamedevelopment.subscriptionplan'),
        ),
    ]
