# Generated by Django 5.1.5 on 2025-08-31 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0006_usersubscription_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('win_games', 'Win X Games'), ('win_pair', 'Win with a Pair'), ('win_high_card', 'Win with High Card')], max_length=50)),
                ('goal', models.PositiveIntegerField()),
                ('reward', models.PositiveIntegerField()),
                ('is_vip_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedevelopment.challenge')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('player', 'challenge')},
            },
        ),
    ]
