# Generated by Django 5.1.5 on 2025-08-31 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0007_challenge_playerchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerchallenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
