# Generated by Django 5.1.5 on 2025-09-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0008_playerchallenge_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='is_vip_only',
        ),
        migrations.AddField(
            model_name='challenge',
            name='assigned_to_all',
            field=models.BooleanField(default=True),
        ),
    ]
