# Generated by Django 5.1.5 on 2025-02-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0008_alter_gametable_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_packed',
            field=models.BooleanField(default=False),
        ),
    ]
