# Generated by Django 5.1.5 on 2025-02-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0009_player_is_packed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='round_status',
            field=models.CharField(choices=[('betting', 'Betting'), ('distribution', 'Distribution'), ('waiting', 'Waiting'), ('showdown', 'Showdown')], default='Waiting', max_length=50),
        ),
    ]
