# Generated by Django 5.1.5 on 2025-09-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0009_remove_challenge_is_vip_only_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='assigned_to_all',
            new_name='assign_to_all',
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_vip_only',
            field=models.BooleanField(default=False),
        ),
    ]
