# Generated by Django 5.1.5 on 2025-09-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0010_rename_assigned_to_all_challenge_assign_to_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='type',
            field=models.CharField(choices=[('games', 'Games'), ('pair', 'Pair'), ('high_card', 'High Card')], max_length=50),
        ),
    ]
