# Generated by Django 5.1.5 on 2025-02-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0011_alter_gametable_round_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='round_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('betting', 'Betting'), ('distribution', 'Distribution'), ('showdown', 'Showdown')], default='waiting', max_length=50),
        ),
    ]
