# Generated by Django 5.1.5 on 2025-02-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0013_gametable_last_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametable',
            name='last_active',
        ),
    ]
