# Generated by Django 5.1.5 on 2025-03-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0018_alter_gametable_current_pot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='current_pot',
            field=models.IntegerField(default=0),
        ),
    ]
