# Generated by Django 5.1.5 on 2025-03-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0019_alter_gametable_current_pot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
