# Generated by Django 5.1.5 on 2025-07-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0020_alter_gametable_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehistory',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamehistory',
            name='player',
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='game_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='player_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
