# Generated by Django 5.1.5 on 2025-07-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0021_remove_gamehistory_game_remove_gamehistory_player_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamehistory',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='gamehistory',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RemoveField(
            model_name='gamehistory',
            name='username',
        ),
    ]
