# Generated by Django 5.1.5 on 2025-07-06 07:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0022_rename_game_id_gamehistory_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gamedevelopment.gametable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gamedevelopment.player'),
            preserve_default=False,
        ),
    ]
