# Generated by Django 5.1.5 on 2025-07-09 09:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0025_gamehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'table')},
        ),
    ]
