# Generated by Django 5.1.5 on 2025-07-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0029_alter_gametable_table_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='ordered_players',
            field=models.JSONField(default=list),
        ),
    ]
