# Generated by Django 5.1.5 on 2025-07-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0030_gametable_ordered_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametable',
            name='ordered_players',
        ),
    ]
