# Generated by Django 5.1.5 on 2025-07-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0031_remove_gametable_ordered_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='disconnected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
