# Generated by Django 5.1.5 on 2025-02-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0002_gametable_created_by_gametable_is_private_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='action',
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_action',
            field=models.CharField(choices=[('blind', 'Blind'), ('chaal', 'Chaal'), ('pack', 'Pack'), ('sideshow', 'Sideshow')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gametable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_turn',
            field=models.BooleanField(default=False),
        ),
    ]
