# Generated by Django 5.1.5 on 2025-02-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0005_remove_player_is_packed_alter_gametable_round_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='hand',
            new_name='hand_cards',
        ),
        migrations.AddField(
            model_name='gametable',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
    ]
