# Generated by Django 5.1.5 on 2025-02-10 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0012_alter_gametable_round_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
