# Generated by Django 5.1.5 on 2025-02-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0014_remove_gametable_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='max_players',
            field=models.IntegerField(default=3),
        ),
    ]
