# Generated by Django 5.1.5 on 2025-03-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0016_delete_card_alter_bet_bet_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='round_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('betting', 'Betting'), ('distribution', 'Distribution'), ('showdown', 'Showdown')], max_length=50),
        ),
    ]
