# Generated by Django 5.1.5 on 2025-03-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0017_alter_gametable_round_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='current_pot',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
