# Generated by Django 5.1.5 on 2025-07-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0023_alter_gamehistory_game_alter_gamehistory_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameHistory',
        ),
    ]
