# Generated by Django 5.1.5 on 2025-07-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedevelopment', '0027_player_is_spectator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='round_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('betting', 'Betting'), ('distribution', 'Distribution'), ('showdown', 'Showdown'), ('showdown_after_pack', 'Showdown After Pack')], default='waiting', max_length=50),
        ),
    ]
